apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false

  tagPolicy:
    sha256: {}

  artifacts:
  - image: employee-api
    context: "."
    docker:
      dockerfile: dockerfiles/Dockerfile
      noCache: false

deploy:
  helm:
    releases:
    - name: employee-api
      chartPath: chart

portForward:
- resourceType: service
  resourceName: employee-api-svc
  port: 80
  address: 0.0.0.0
  localPort: 8000
